<?php 
session_start();
if (isset($_SESSION['username'])) {
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ประกาศข่าว</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>
<script type="text/javascript" src="../js/jquery-1.10.2.min.js"></script>

<script type="text/javascript">

$(document).ready(function(){

  $("#element_7_1").click(function(){
     $("#li_2").hide();
     $("#li_3").show();
  });
  $("#element_7_2").click(function(){
      $("#li_2").show();
     $("#li_3").hide();
  });
 
 
});

</script>

</head>
<body id="main_body" >
	
	<img id="top" src="images/top.png" alt="">
	<div id="form_container">
		<h1>&nbsp;
		<span> <?='Hello, ' . $_SESSION['username']?> <a href="logout.php">(ออกจากระบบ)</a></h1>
		<form id="file_upload" class="appnitro" enctype="multipart/form-data" method="post" action="post.php">
					<div class="form_description">
			<h2>ประกาศข่าว</h2>
			<p>ประชาสัมพันธ์ข่าวสารบนเว็บไซต์</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="detail">หัวข้อข่าว </label>
		<div>
			<textarea id="detail" name="detail" class="element textarea small"></textarea> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="newsType">ประเภทข่าว </label>
		<div>
		<select class="element select medium" id="newsType" name="newsType"> 
			<option value="1" selected="selected">ข่าวประชาสัมพันธ์</option>
<option value="2" >ข่าวสำหรับนักศึกษา</option>
<option value="3" >ข่าวรับสมัครงาน</option>
<option value="4" >ข่าวจัดซื้อจัดจ้าง</option>

		</select>
		</div> 
		</li>		
		</li>		<li id="li_7" >
		<label class="description" for="linkrdo">ชนิดลิงค์ของข่าว</label>
		<span>
			<input id="element_7_1" name="linkrdo" class="element radio" type="radio" value="1" checked="checked"  />
<label class="choice" for="element_7_1">แนบไฟล์ข่าว</label>
<input id="element_7_2" name="linkrdo" class="element radio" type="radio" value="2"  />
<label class="choice" for="element_7_2">ลิงค์ข่าวปลายทาง</label>
		</span> 
		</li>
		
		<li id="li_2" style="display:none">
		<label class="description" for="linkURL">ลิงค์ข่าว </label>
		<div>
			<input id="linkURL" name="linkURL" class="element text medium" type="text" maxlength="255" value="http://"/> 
		</div> 
		</li>		
		
		<li id="li_3" >
		<label class="description" for="file">เอกสารไฟล์แนบ </label>
		<div>
			<input id="file" name="file" class="element file" type="file"/> 
		</div>  
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="execute" id="execute">
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="images/bottom.png" alt="">
	</body>
</html>

<?php
}
else{
    echo 'Access denied. Please log in!.';
    print '<META HTTP-EQUIV="Refresh" CONTENT="1;URL=index.php">';
}
?>